title: Nicky Nickell
author:
  name: Nicky Nickell
  email: nicky.nickell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about whatever random shiny I happen to be working on. May contain 
  open source, game dev, mods, cpu design, and trace amounts of obscure RFCs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cadpnq.github.io"

show_excerpts: true

minima:
  skin: dark
  social_links:
    github: cadpnq

header_pages:
  - portfolio.md
  - about.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
